### ISSUE TITLE
Put AWS SDK in the AMI

### ISSUE THREAD

**Issue by kc1212** [aaronang/cong-the-ripper#43]
`go get` spends most of the time downloading the AWS SDK.

benchmark when AWS SDK is available
```
[centos@ip-172-31-36-252 ~]$ time go get github.com/aaronang/cong-the-ripper/cmd/master

real    0m4.204s
user    0m2.751s
sys     0m0.312s

```

benchmark for when AWS is not available
```
[centos@ip-172-31-36-252 ~]$ time go get github.com/aaronang/cong-the-ripper/cmd/master

real    0m24.920s
user    0m13.443s
sys     0m1.141s

```

**Comment by aaronang** [comment]
Note that AWS SDK is only required in the master instances. In addition, I found out that using `go get` on boot somehow always take longer than 30 seconds.

With AWS SDK available.

```
$ time go get -u github.com/aaronang/cong-the-ripper/cmd/master

real    0m46.771s
user    0m11.488s
sys     0m0.997s
```

Without AWS SDK available.

```
$ time go get -u github.com/aaronang/cong-the-ripper/cmd/master

real    0m51.778s
user    0m14.912s
sys     0m1.440s
```

**Comment by aaronang** [comment]
This issue is closed because an AMI is created that includes the Go AWS SDK.
